---
- name: Making sure the required directories exist
  ansible.builtin.file:
    path: "{{ item | dirname }}"
    owner: "{{ owner }}"
    group: docker
    state: directory
    mode: 0755
  loop: "{{ files | map(attribute='destination_path') | list | unique }}"
  loop_control:
    label: "{{ item | dirname }}"

- name: Copying files
  ansible.builtin.copy:
    src: "{{ item.source_path }}"
    dest: "{{ item.destination_path }}"
    owner: "{{ owner }}"
    group: docker
    # Secrets must be readable by all users to be used by the docker container
    mode: 0644
  loop: "{{ files }}"
  loop_control:
    label: "{{ item.destination_path }}"
  register: copy_files
  notify: restart docker compose
