---
- name: Making sure the required directories exist for files
  ansible.builtin.file:
    path: "{{ item | dirname }}"
    owner: "{{ item.owner | default(owner) }}"
    group: "{{ item.group | default(group) }}"
    state: directory
    mode: 0755
  loop: "{{ files | map(attribute='destination_path') | list | unique }}"
  loop_control:
    label: "{{ item | dirname }}"

- name: Copying files
  ansible.builtin.copy:
    src: "{{ item.source_path }}"
    dest: "{{ item.destination_path }}"
    owner: "{{ item.owner | default(owner) }}"
    group: "{{ item.group | default(group) }}"
    # Secrets must be readable by all users to be used by the docker container
    mode: 0644
  loop: "{{ files }}"
  loop_control:
    label: "{{ item.destination_path }}"
  register: copy_files
  notify: restart containers after updating files

- name: Making sure the required directories exist for templates
  ansible.builtin.file:
    path: "{{ item | dirname }}"
    owner: "{{ item.owner | default(owner) }}"
    group: "{{ item.group | default(group) }}"
    state: directory
    mode: 0755
  loop: "{{ templates | map(attribute='destination_path') | list | unique }}"
  loop_control:
    label: "{{ item | dirname }}"

- name: Copying templates
  ansible.builtin.template:
    src: "{{ item.source_path }}"
    dest: "{{ item.destination_path }}"
    owner: "{{ item.owner | default(owner) }}"
    group: "{{ item.group | default(group) }}"
    mode: 0644
  when: templates
  loop: "{{ templates }}"
  loop_control:
    label: "{{ item.destination_path }}"
  register: copy_templates
  notify: restart containers after updating templates
